XDS.ONLINE.WEB/Controllers/CustomVettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XDS.ONLINE.ENGINE;
using XDS.ONLINE.MODELS;
using System.Threading.Tasks;
using System.Web.Routing;
using System.Xml.Linq;
using System.Xml;
using System.Globalization;

namespace XDS.ONLINE.WEB.Controllers
{
    public class CustomVettingController : BaseXDSEngineController
    {

        public CustomVettingController()
        {
        }

        public CustomVettingController(IXDSServiceEngine serviceEngine)
        {
            _serviceEngine = serviceEngine;
        }

        //
        // GET: /CustomVetting/
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> CustomVettingMatch()
        {
            ViewBag.Message = "Your create enquiry page.";
            ViewBag.ProductID = "110";

            string transactionDetails = _serviceEngine.CustomVettingGetTransactionDetails(Session["AuthToken"].ToString());

            CustomVettingMatchViewModel em = new CustomVettingMatchViewModel(transactionDetails);
            ViewData["PromotionDealList"] = em.PromotionDealList;
            return View(em);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CustomVettingMatch(CustomVettingMatchViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Message = "Your create enquiry page.";
                ViewBag.ProductID = "110";

                string transactionDetails = _serviceEngine.CustomVettingGetTransactionDetails(Session["AuthToken"].ToString());
                CustomVettingMatchViewModel em = new CustomVettingMatchViewModel(transactionDetails);

                model.DealerList = em.DealerList;
                model.PromotionDealList = em.PromotionDealList;
                model.PromoCodeList = em.PromoCodeList;
                model.ProductID = 110;
                // return View(model);
                return PartialViewHelper("CustomVettingMatch", model);
            }

            string transactionDetailstemp = _serviceEngine.CustomVettingGetTransactionDetails(Session["AuthToken"].ToString());
            string promotionDealValue = string.Empty;

            System.Xml.XmlDocument doc = new System.Xml.XmlDocument();
            doc.LoadXml(transactionDetailstemp);
            System.Xml.XmlNodeList nodeList = doc.SelectNodes("//TransactionDetails/Dealer");
            System.Xml.XmlNodeList nodeList2 = doc.SelectNodes("//TransactionDetails/PromotionDeal");
            System.Xml.XmlNodeList nodeList3 = doc.SelectNodes("//TransactionDetails/PromoCode");

            foreach (System.Xml.XmlNode node2 in nodeList2)
                if (node2["PromotionDealID"].InnerText == model.PromotionValue)
                {
                    promotionDealValue = node2["DealSheetNo"].InnerText.ToString();
                }

            


            string strUsername = Session["UserName"] != null ? Session["UserName"].ToString() : string.Empty;

            CustomVetting rpt = null;
            ListofHistory listOfHistory = null;

            listOfHistory = await _serviceEngine.CustomVettingGetTransactionHistoryAsync(Session["AuthToken"].ToString(), Session["UserName"].ToString(), model.IdNumber == null ? "" : model.IdNumber,
                  "", "", DateTime.Now.AddDays(-30), DateTime.Now, true);

            if (listOfHistory != null && listOfHistory.SearchHistory.Count() > 0)
                return PartialViewHelper("_CustomVettingReportPartial", "Customer has been submitted within the last 30 days");
            else
            {
                rpt = await _serviceEngine.ConnectCustomVettingNAsync(Session["XDSWSAuthToken"].ToString(), model.ProductID, model.IdNumber, model.FirstName, model.Surname, model.DateOfBirth, model.Income, model.MobileNo,
                    model.AlternateMobileNo, model.Email, model.DealerValue, model.PromotionValue, model.PromoCodeValue, strUsername, DateTime.Now,promotionDealValue);

                Session["ReportXML"] = _serviceEngine.ReportXML();

                if (rpt != null && rpt.CustomVettingResult.Count() > 0)
                {
                    CustomVettingResult oCustomVettingResult = rpt.CustomVettingResult[0];

                    #region[ Log Transaction ] 
                    string strResult = string.Empty;

                    if (string.IsNullOrEmpty(model.City))
                    {
                        model.City = string.Empty;
                    }

                    float Latitude = 0;
                    float Longitude = 0;

                    float.TryParse(model.Latitude,NumberStyles.Float, CultureInfo.InvariantCulture.NumberFormat,out Latitude);
                    float.TryParse(model.Longitude, NumberStyles.Float, CultureInfo.InvariantCulture.NumberFormat, out Longitude);


                    strResult = await _serviceEngine.LogTransactionAsync(Session["AuthToken"].ToString(),
                        oCustomVettingResult.ApplicationPromotionDeal, oCustomVettingResult.ApplicationDealerID, oCustomVettingResult.PromoCode, oCustomVettingResult.FirstName,
                        oCustomVettingResult.Surname, General.DisplayDateWithTime(oCustomVettingResult.BirthDate),
                        oCustomVettingResult.IDNo, oCustomVettingResult.Income, oCustomVettingResult.CellularNo,
                        oCustomVettingResult.AlternateContactNo, oCustomVettingResult.EmailAddress, oCustomVettingResult.ReferenceNo, oCustomVettingResult.Score,
                        oCustomVettingResult.ReasonCode, oCustomVettingResult.ApplicationStatus, oCustomVettingResult.Portfolio,
                        General.DisplayDateWithTime(oCustomVettingResult.CreatedOnDate),
                        oCustomVettingResult.ReasonDescription, oCustomVettingResult.CapturedBy, oCustomVettingResult.ConsumerID.ToString(),
                        oCustomVettingResult.PredictedIncome, oCustomVettingResult.PredictedAvailableInstalment,
                        oCustomVettingResult.AccountNo, oCustomVettingResult.SourceInd, oCustomVettingResult.VodacomResponse, oCustomVettingResult.VodacomResponseType, oCustomVettingResult.EmailStatus, Latitude, Longitude, model.City);
                    #endregion

                    #region[ Send SMS ]
                    if (!oCustomVettingResult.ApplicationStatus.ToLower().Trim().StartsWith("apply") && !oCustomVettingResult.Portfolio.ToLower().Trim().StartsWith("apply"))
                    {
                        ListofSMSConfig ListofSMSConfig = null;
                        SMSResult oSMSResult = null;

                        string strSMSMessage = string.Empty;
                        int EnquiryID = 0;

                        ListofSMSConfig = await _serviceEngine.GetSMSConfigAsync(Session["AuthToken"].ToString());

                        if (ListofSMSConfig != null && ListofSMSConfig.SMSConfigList.Count() > 0)
                        {
                            strSMSMessage = ListofSMSConfig.SMSConfigList[0].SMSMessage.Replace("##RefNo##", oCustomVettingResult.IDNo);
                            int.TryParse(oCustomVettingResult.EnquiryID.ToString(), out EnquiryID);

                            oSMSResult = await _serviceEngine.SMSAlertAsync(Session["XDSWSAuthToken"].ToString(),
                                !string.IsNullOrEmpty(model.MobileNo) ? model.MobileNo : model.AlternateMobileNo, strSMSMessage, Session["SMSAlertType"].ToString(), EnquiryID, int.Parse(Session["SMSProductID"].ToString()));
                        }
                    }
                    #endregion
                }
            }

            return PartialViewHelper("_CustomVettingReportPartial", rpt);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CustomVettingHistoryReport(HistoryMatchViewModel model)
        {
            //ViewBag.Message = "Your create enquiry page.";
            if (ModelState.IsValid)
            {
                CustomVetting rpt = null;

                rpt = await _serviceEngine.CustomVettingGetTransactionEnquiryAsync(Session["AuthToken"].ToString(), model.EnquiryID);

                Session["ReportXML"] = _serviceEngine.ReportXML();

                return PartialViewHelper("_CustomVettingReportPartial", rpt);

            }
            return null;
        }
    }
}

XDS.ONLINE.WEB/Controllers/PromotionDealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XDS.ONLINE.ENGINE;
using XDS.ONLINE.MODELS;
using System.Threading.Tasks;
using System.Web.Routing;
using System.Xml.Linq;
using System.Xml;

namespace XDS.ONLINE.WEB.Controllers
{
    public class PromotionDealController : BaseXDSEngineController
    {

        public PromotionDealController()
        {
        }

        public PromotionDealController(IXDSServiceEngine serviceEngine)
        {
            _serviceEngine = serviceEngine;
        }

        //
        // GET: /CustomVetting/
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> PromotionDealMatch()
        {
            ViewBag.Message = "";
            ViewBag.ProductID = "110";

            ListofPromotionDeals em = new ListofPromotionDeals();

            em = await _serviceEngine.GetPromotionDealsAsync(Session["AuthToken"].ToString(), 0);

            return View(em);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PromotionDealMatch(string Portfolio)
        {
            ListofPromotionDeals em = null;

            em = _serviceEngine.GetPromotionDealsByPortfolio(Session["AuthToken"].ToString(), Portfolio);

            return View(em);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetPromotionDeal(long PromotionDealID)
        {
            ListofPromotionDeals em = null;
            ListofPortfolios emPortfolio = null;

            PromotionDealItem oPromotionDealItem = null;

            em = _serviceEngine.GetPromotionDeals(Session["AuthToken"].ToString(), PromotionDealID);
            emPortfolio = _serviceEngine.GetPortfoliosByPromotionDeal(Session["AuthToken"].ToString(), PromotionDealID);

            if (em != null && em.PromotionDealList.Count() > 0)
            {
                oPromotionDealItem = em.PromotionDealList[0];

                oPromotionDealItem.PromotionDealPortfolios = emPortfolio;

                if (oPromotionDealItem.Doc != null)
                    oPromotionDealItem.Image = string.Format("data:{0};base64,{1}", oPromotionDealItem.DocContentType, Convert.ToBase64String(oPromotionDealItem.Doc));
            }

            return PartialView("_PromotionDealPartial", oPromotionDealItem);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetPortfoliosByPromotionDeal(long PromotionDealID)
        {
            ListofPortfolios em = null;

            em = _serviceEngine.GetPortfoliosByPromotionDeal(Session["AuthToken"].ToString(), PromotionDealID);

            return PartialView("_PortfolioPartial", em);
        }
    }
}

XDS.ONLINE.WEB/Controllers/ReportExportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XDS.ONLINE.ENGINE;
using XDS.ONLINE.ENGINE.REPORTGENERATOR;
using XDS.ONLINE.MODELS;

namespace XDS.ONLINE.WEB.Controllers
{
    public class ReportExportController : BaseController
    {
        private readonly IXDSReportExporter _reportExporter;

        public ReportExportController(IXDSReportExporter XDSReportExporter)
        {
            _reportExporter = XDSReportExporter;
        }

        // GET: ReportExport
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetReport(string EnquiryID, string EnquiryResultID, string Format, int ProductID, string Format1, string EnquiryResultID1)
        {
            Format = Format == null ? Format1 : Format;
            EnquiryResultID = EnquiryResultID == null ? EnquiryResultID1 : EnquiryResultID; 
            string XmlData = "";
            string Reference = "";
            string ContentType = "";
            string FileName = "";

            XmlData = Session["ReportXML"] != null ? Session["ReportXML"].ToString() : "";
            Reference = Guid.NewGuid().ToString();

            byte[] ReportBinary = null;
            Types.ReportFormat fmt = Types.ReportFormat.pdf;

            switch (Format.ToLower())
            {
                case "pdf":
                    fmt = Types.ReportFormat.pdf;
                    FileName = string.Concat(Reference.Replace('-', '_'), ".pdf");
                    ContentType = "application/pdf";
                    break;

                case "html":
                    fmt = Types.ReportFormat.html;
                    FileName = string.Concat(Reference.Replace('-', '_'), ".mht");
                    ContentType = "text/html";
                    break;

                case "image":
                    fmt = Types.ReportFormat.image;
                    FileName = string.Concat(Reference.Replace('-', '_'), ".jpg");
                    ContentType = "image/jpeg";
                    break;
            }

            ReportBinary = _reportExporter.GenerateReport(XmlData, fmt, ProductID);

            ViewBag.ContentType = ContentType;
            ViewBag.ReportName = FileName;
            ViewBag.ReportBinary = ReportBinary;

            return View();
        }


        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmailReport(string EnquiryID, string EnquiryResultID, int ProductID)
        {
            EmailReportViewModel model = new EmailReportViewModel();
            model.FromName = Session["DisplayName"].ToString() ;
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmailReportSend(EmailReportViewModel model)
        {
            string XmlData = "";
            string Reference = "";
            string response = "";

            if (ModelState.IsValid)
            { 
            // todo: generate binary and send email
                 if (Session["EnquiryResultID"].ToString() == model.EnquiryResultID.ToString())
                  {
                      XmlData = Session["ReportXML"].ToString();
                      Reference = Guid.NewGuid().ToString();
                  }
                 else
                 {
                     throw new Exception("Report data has been refreshed.");
                 }

                if (_reportExporter.EmailReport(Session["DisplayName"].ToString(), model.ReplyToEmailAddress, model.ToEmailAddress, model.EmailBody, XmlData, model.ProductID))
                {
                    response = "The email has been sent.";
                }
                else
                {
                    response = "There has been a problem with your request. Please check your input and try again.";
                }
            }else{
                response="There has been a problem with your request. Please check your input and try again.";
            }
            if (Request.IsAjaxRequest())
            {
                return Content(response , "text/html");
            }
            return View();
        }
    
    }
}

XDS.ONLINE.WEB/Views/CustomVetting/CustomVettingMatch.cshtml
@model XDS.ONLINE.MODELS.CustomVettingMatchViewModel

@{
    ViewBag.Title = "Vetting Application";
}

<div id="reportsection" style="display:none;">
    <div id="reportnav">
        @Html.Partial("~/Views/Shared/_TopBarReportPartial.cshtml")


        @using (Html.BeginForm("GetReport", "ReportExport", FormMethod.Post, new { id = "reportform" }))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden("ConsumerID", "")
            @Html.Hidden("EnquiryResultID", "")
            @Html.Hidden("Format", "")
            @Html.Hidden("ProductID", (string)ViewBag.ProductID)
        }
    </div>
    <div id="reportdetail"></div>
</div>

<div id="searchsection">
    <div id="searchinput">

        @using (Html.BeginForm("CustomVettingMatch", "CustomVetting", FormMethod.Post, new { id = "searchform" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true) 
            @Html.Hidden("ProductID", (string)ViewBag.ProductID)
            @Html.HiddenFor(model => model.Latitude, new { id = "Latitude" })
            @Html.HiddenFor(model => model.Longitude, new { id = "Longitude" })
            @Html.HiddenFor(model => model.City, new { id = "City" })


            <fieldset>
                <legend>Customer Information</legend>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.DealerValue, new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.DealerValue, new SelectList(Model.DealerList, "DealerID", "DealerName"), string.Empty, new { @class = "form-control",id= "ddvettingDealer" })
                        @Html.ValidationMessageFor(model => model.DealerValue)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.PromotionValue, new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.PromotionValue, new SelectList(Model.PromotionDealList, "PromotionDealID", "Description"), string.Empty, new { @class = "form-control", id = "ddvettingPromotion" })
                        @Html.ValidationMessageFor(model => model.PromotionValue)
                        
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.PromoCodeValue, new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.PromoCodeValue, new SelectList(Model.PromoCodeList, "Description", "Description"), string.Empty, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PromoCodeValue)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.IdNumber, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.IdNumber, new { @class = "form-control", placeholder = "Enter ID Number", maxlength = 13 })
                        @Html.ValidationMessageFor(model => model.IdNumber)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Surname, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.Surname, new { @class = "form-control", placeholder = "Enter Surname" })
                        @Html.ValidationMessageFor(model => model.Surname)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.FirstName, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control", placeholder = "Enter Firstname" })
                        @Html.ValidationMessageFor(model => model.FirstName)
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class='input-group date'>
                            @Html.LabelFor(model => model.DateOfBirth, new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.DateOfBirth, new { @class = "form-control", placeholder = "yyyy/mm/dd", id = "DateOfBirth" })
                            @Html.ValidationMessageFor(model => model.DateOfBirth)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Income, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.Income, new { @class = "form-control", placeholder = "Enter Income", maxlength = 10 })
                        @Html.ValidationMessageFor(model => model.Income)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.MobileNo, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.MobileNo, new { @class = "form-control", placeholder = "Enter Your Mobile Number", maxlength = 10 })
                        @Html.ValidationMessageFor(model => model.MobileNo)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.AlternateMobileNo, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.AlternateMobileNo, new { @class = "form-control", placeholder = "Enter Your Alternate Contact Number", maxlength = 10 })
                        @Html.ValidationMessageFor(model => model.AlternateMobileNo)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control", placeholder = "Enter Your Email Address" })
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Consent, new { @class = "control-label" })
                        @Html.CheckBoxFor(model => model.Consent, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Consent)
                    </div>
                </div>
                <div class="col-md-12">
                    <input type="submit" id="searchbutton" class="btn btn-primary" onclick="CustomVettingMatch(); return false;" value="Submit" />
                    <input type="button" id="clearbutton" class="btn btn-primary" onclick="CustomVettingClear(); return false;" value="Clear" />
                </div>
            </fieldset>
        }

    </div>
    <div id="ConsumerResults">
    </div>
</div>
 

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datepicker")

    <script type="text/javascript">
        $(function () {
            $("#ddvettingDealer").chosen();
            $("#ddvettingPromotion").chosen();
            
          
            BonusXmlUrl = '';
            ReportUrl = '@Url.Action("CustomVettingReport", "CustomVetting")';

            //$('#Consent').change(function () {
            //    if ($(this).is(":checked"))
            //        $('#searchbutton').removeAttr('disabled');
            //    else
            //        $("#searchbutton").attr("disabled", true);
            //});

            InitializeCustomVettingReport();
        });

        // extend jquery range validator to work for required checkboxes
        var defaultRangeValidator = $.validator.methods.range;
        $.validator.methods.range = function (value, element, param) {
            if (element.type === 'checkbox') {
                // if it's a checkbox return true if it is checked
                return element.checked;
            } else {
                // otherwise run the default validation function
                return defaultRangeValidator();
            }
        }


        if(Modernizr.geolocation){
            navigator.geolocation.getCurrentPosition(success, error);
        }
        else if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(success1, error1);
        }
        else {
            alert("location sedrvices are not supported on your device ");
            $('#Latitude').val('0');
            $('#Longitude').val('0');

        }


        function success(position) {
            var lat = position.coords.latitude;
            var long = position.coords.longitude;
            var city = position.coords.locality;
            var myLatlng = new google.maps.LatLng(lat, long);
            var myOptions = {
                center: myLatlng,
                zoom: 12,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            $('#Latitude').val(lat);
            $('#Longitude').val(long);
            $('#City').val(city);


        }
        function error(error) {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(success1, error1);
            }
            else {
                if (error.code === 1) {
                    alert(error.message);
                }
                else if (error.code === 2) {
                    alert(error.message);
                }
                else if (error.code === 3) {
                    alert(error.message);
                }
                else {
                    alert(error.message);
                }

                $('#Latitude').val('0');
                $('#Longitude').val('0');
            }
        }

        function success1(position) {
            var lat = position.coords.latitude;
            var long = position.coords.longitude;
            var city = position.coords.locality;
            var myLatlng = new google.maps.LatLng(lat, long);
            var myOptions = {
                center: myLatlng,
                zoom: 12,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            $('#Latitude').val(lat);
            $('#Longitude').val(long);
            $('#City').val(city);


        }
        function error1(error) {
            //if (geoPosition.init) {
            //    geoPosition.getCurrentPosition(success2, error2);
            //}
            //else {
            if (error.code === 1) {
                alert(error.message);
                }
            else if (error.code === 2) {
                    alert(error.message);
                }
            else if (error.code === 3) {
                alert(error.message);
                }
                else {
                alert(error.message);
                }

                $('#Latitude').val('0');
                $('#Longitude').val('0');
            //}
        }

        //function success2(position) {
        //    var lat = position.coords.latitude;
        //    var long = position.coords.longitude;
        //    var city = position.coords.locality;
        //    var myLatlng = new google.maps.LatLng(lat, long);
        //    var myOptions = {
        //        center: myLatlng,
        //        zoom: 12,
        //        mapTypeId: google.maps.MapTypeId.ROADMAP
        //    };

        //    $('#Latitude').val(lat);
        //    $('#Longitude').val(long);
        //    $('#City').val(city);


        //}
        //function error2(error) {
        //    if (error === 1) {
        //        alert("unable to get location coordinates");
        //    }
        //    else if (error === 2) {
        //        alert("GeoPosition is unavailable");
        //    }
        //    else if (error === 3) {
        //        alert("Time Out...request taking too long.");
        //    }
        //    else {
        //        alert("Location services not active or allowed on your device");
        //    }

        //    $('#Latitude').val('0');
        //    $('#Longitude').val('0');
        //}
</script>
}

XDS.ONLINE.WEB/Views/CustomVetting/_CustomVettingReportPartial.cshtml
@model XDS.ONLINE.MODELS.CustomVetting

<div class="panel panel-primary">
    <div class="panel-heading">Result Summary</div>
    <div class="panel-body">

        @if (Model.CustomVettingResult.Count() > 0)
        {
            @Html.Hidden("EnquiryID", @Model.CustomVettingResult[0].EnquiryID)

            <div class="row">
                <div class="col-md-3">Reference No.:</div>
                <div class="col-md-3"><strong>@Model.CustomVettingResult[0].ReferenceNo</strong></div>
                <div class="col-md-3">Application Date</div>
                <div class="col-md-3"><strong>@(XDS.ONLINE.MODELS.General.DisplayDateWithTime(@Model.CustomVettingResult[0].CreatedOnDate))</strong></div>
            </div>
            <div class="row">
                <div class="col-md-3">ID No:</div>
                <div class="col-md-3"><strong>@Model.CustomVettingResult[0].IDNo</strong></div>
                <div class="col-md-3">Date of Birth:</div>
                <div class="col-md-3"><strong>@(XDS.ONLINE.MODELS.General.DisplayDate(@Model.CustomVettingResult[0].BirthDate))</strong></div>
            </div>
            <div class="row">
                <div class="col-md-3">Surname:</div>
                <div class="col-md-3"><strong>@Model.CustomVettingResult[0].Surname</strong></div>
                <div class="col-md-3">First Name:</div>
                <div class="col-md-3"><strong>@Model.CustomVettingResult[0].FirstName</strong></div>
            </div>
            <div class="row">
                <div class="col-md-3">Cellular/Mobile No:</div>
                <div class="col-md-3"><strong>@Model.CustomVettingResult[0].CellularNo</strong></div>
                <div class="col-md-3">Alternate Contact No:</div>
                <div class="col-md-3"><strong>@Model.CustomVettingResult[0].AlternateContactNo</strong></div>
            </div>
            <div class="row">
                <div class="col-md-3">Email Address:</div>
                <div class="col-md-3"><strong>@Model.CustomVettingResult[0].EmailAddress</strong></div>
                <div class="col-md-3">Captured By:</div>
                <div class="col-md-3"><strong>@Model.CustomVettingResult[0].CapturedBy</strong></div>
            </div>
            <div class="row">
                <div class="col-md-3">Application Status:</div>
                <div class="col-md-3"><strong>@Model.CustomVettingResult[0].ApplicationStatus</strong></div>
                <div class="col-md-3">Portfolio:</div>
                <div class="col-md-3 portfoliolink"><strong>@Model.CustomVettingResult[0].Portfolio</strong></div>
            </div>
            <div class="row">
                <div class="col-md-3">Dealer ID:</div>
                <div class="col-md-3"><strong>@Model.CustomVettingResult[0].DealerID</strong></div>
                <div class="col-md-3">Promo Code:</div>
                <div class="col-md-3"><strong>@Model.CustomVettingResult[0].PromoCode</strong></div>
            </div>
        }
    </div>
</div> 

<div id="portfoliosection">
    <div id="reportnav">
        @using (Html.BeginForm("PromotionDealMatch", "PromotionDeal", FormMethod.Post, new { id = "portfolioform" }))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden("Portfolio", "")
        }
    </div>
</div>

<script>
    $(function () {
        $(".portfoliolink").each(function () {
            $(this).click(function () {

                var portfolio = $(this).text(); 
                GetPromotionDealByPortfolio(portfolio);

                return false;
            });
        });
    });
</script>