XDS.ONLINE.WEB/Controllers/BulletinController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XDS.ONLINE.ENGINE;
using XDS.ONLINE.MODELS;
using System.Threading.Tasks;
using System.Web.Routing;
using System.Xml.Linq;
using System.Xml;

namespace XDS.ONLINE.WEB.Controllers
{
    public class BulletinController : BaseXDSEngineController
    {

        public BulletinController()
        {
        }

        public BulletinController(IXDSServiceEngine serviceEngine)
        {
            _serviceEngine = serviceEngine;
        }

        //
        // GET: /CustomVetting/
        public ActionResult Index()
        {
            return View();
        } 

        [HttpGet]
        public async Task<ActionResult> BulletinMatch()
        {
            ViewBag.Message = "";
            ViewBag.ProductID = "110";

            ListofBulletins em = new ListofBulletins();

            em = await _serviceEngine.CustomVettingGetBulletinsAsync(Session["AuthToken"].ToString()); 

            return View(em);
        } 

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DownloadBulletin(long BulletinID)
        {
            ListofBulletins em = null;

            em = _serviceEngine.CustomVettingGetBulletinFile(Session["AuthToken"].ToString(), BulletinID);

            if (em != null && em.BulletinList.Count() > 0)
            {
                ViewBag.ContentType = "application/pdf";
                ViewBag.ReportName = em.BulletinList[0].DocFileName;
                ViewBag.ReportBinary = em.BulletinList[0].Doc;
            }

            return View();
        }
    }
}

XDS.ONLINE.WEB/Controllers/CustomVettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XDS.ONLINE.ENGINE;
using XDS.ONLINE.MODELS;
using System.Threading.Tasks;
using System.Web.Routing;
using System.Xml.Linq;
using System.Xml;
using System.Globalization;

namespace XDS.ONLINE.WEB.Controllers
{
    public class CustomVettingController : BaseXDSEngineController
    {

        public CustomVettingController()
        {
        }

        public CustomVettingController(IXDSServiceEngine serviceEngine)
        {
            _serviceEngine = serviceEngine;
        }

        //
        // GET: /CustomVetting/
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> CustomVettingMatch()
        {
            ViewBag.Message = "Your create enquiry page.";
            ViewBag.ProductID = "110";

            string transactionDetails = _serviceEngine.CustomVettingGetTransactionDetails(Session["AuthToken"].ToString());

            CustomVettingMatchViewModel em = new CustomVettingMatchViewModel(transactionDetails);
            ViewData["PromotionDealList"] = em.PromotionDealList;
            return View(em);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CustomVettingMatch(CustomVettingMatchViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Message = "Your create enquiry page.";
                ViewBag.ProductID = "110";

                string transactionDetails = _serviceEngine.CustomVettingGetTransactionDetails(Session["AuthToken"].ToString());
                CustomVettingMatchViewModel em = new CustomVettingMatchViewModel(transactionDetails);

                model.DealerList = em.DealerList;
                model.PromotionDealList = em.PromotionDealList;
                model.PromoCodeList = em.PromoCodeList;
                model.ProductID = 110;
                // return View(model);
                return PartialViewHelper("CustomVettingMatch", model);
            }

            string transactionDetailstemp = _serviceEngine.CustomVettingGetTransactionDetails(Session["AuthToken"].ToString());
            string promotionDealValue = string.Empty;

            System.Xml.XmlDocument doc = new System.Xml.XmlDocument();
            doc.LoadXml(transactionDetailstemp);
            System.Xml.XmlNodeList nodeList = doc.SelectNodes("//TransactionDetails/Dealer");
            System.Xml.XmlNodeList nodeList2 = doc.SelectNodes("//TransactionDetails/PromotionDeal");
            System.Xml.XmlNodeList nodeList3 = doc.SelectNodes("//TransactionDetails/PromoCode");

            foreach (System.Xml.XmlNode node2 in nodeList2)
                if (node2["PromotionDealID"].InnerText == model.PromotionValue)
                {
                    promotionDealValue = node2["DealSheetNo"].InnerText.ToString();
                }

            


            string strUsername = Session["UserName"] != null ? Session["UserName"].ToString() : string.Empty;

            CustomVetting rpt = null;
            ListofHistory listOfHistory = null;

            listOfHistory = await _serviceEngine.CustomVettingGetTransactionHistoryAsync(Session["AuthToken"].ToString(), Session["UserName"].ToString(), model.IdNumber == null ? "" : model.IdNumber,
                  "", "", DateTime.Now.AddDays(-30), DateTime.Now, true);

            if (listOfHistory != null && listOfHistory.SearchHistory.Count() > 0)
                return PartialViewHelper("_CustomVettingReportPartial", "Customer has been submitted within the last 30 days");
            else
            {
                rpt = await _serviceEngine.ConnectCustomVettingNAsync(Session["XDSWSAuthToken"].ToString(), model.ProductID, model.IdNumber, model.FirstName, model.Surname, model.DateOfBirth, model.Income, model.MobileNo,
                    model.AlternateMobileNo, model.Email, model.DealerValue, model.PromotionValue, model.PromoCodeValue, strUsername, DateTime.Now,promotionDealValue);

                Session["ReportXML"] = _serviceEngine.ReportXML();

                if (rpt != null && rpt.CustomVettingResult.Count() > 0)
                {
                    CustomVettingResult oCustomVettingResult = rpt.CustomVettingResult[0];

                    #region[ Log Transaction ] 
                    string strResult = string.Empty;

                    if (string.IsNullOrEmpty(model.City))
                    {
                        model.City = string.Empty;
                    }

                    float Latitude = 0;
                    float Longitude = 0;

                    float.TryParse(model.Latitude,NumberStyles.Float, CultureInfo.InvariantCulture.NumberFormat,out Latitude);
                    float.TryParse(model.Longitude, NumberStyles.Float, CultureInfo.InvariantCulture.NumberFormat, out Longitude);


                    strResult = await _serviceEngine.LogTransactionAsync(Session["AuthToken"].ToString(),
                        oCustomVettingResult.ApplicationPromotionDeal, oCustomVettingResult.ApplicationDealerID, oCustomVettingResult.PromoCode, oCustomVettingResult.FirstName,
                        oCustomVettingResult.Surname, General.DisplayDateWithTime(oCustomVettingResult.BirthDate),
                        oCustomVettingResult.IDNo, oCustomVettingResult.Income, oCustomVettingResult.CellularNo,
                        oCustomVettingResult.AlternateContactNo, oCustomVettingResult.EmailAddress, oCustomVettingResult.ReferenceNo, oCustomVettingResult.Score,
                        oCustomVettingResult.ReasonCode, oCustomVettingResult.ApplicationStatus, oCustomVettingResult.Portfolio,
                        General.DisplayDateWithTime(oCustomVettingResult.CreatedOnDate),
                        oCustomVettingResult.ReasonDescription, oCustomVettingResult.CapturedBy, oCustomVettingResult.ConsumerID.ToString(),
                        oCustomVettingResult.PredictedIncome, oCustomVettingResult.PredictedAvailableInstalment,
                        oCustomVettingResult.AccountNo, oCustomVettingResult.SourceInd, oCustomVettingResult.VodacomResponse, oCustomVettingResult.VodacomResponseType, oCustomVettingResult.EmailStatus, Latitude, Longitude, model.City);
                    #endregion

                    #region[ Send SMS ]
                    if (!oCustomVettingResult.ApplicationStatus.ToLower().Trim().StartsWith("apply") && !oCustomVettingResult.Portfolio.ToLower().Trim().StartsWith("apply"))
                    {
                        ListofSMSConfig ListofSMSConfig = null;
                        SMSResult oSMSResult = null;

                        string strSMSMessage = string.Empty;
                        int EnquiryID = 0;

                        ListofSMSConfig = await _serviceEngine.GetSMSConfigAsync(Session["AuthToken"].ToString());

                        if (ListofSMSConfig != null && ListofSMSConfig.SMSConfigList.Count() > 0)
                        {
                            strSMSMessage = ListofSMSConfig.SMSConfigList[0].SMSMessage.Replace("##RefNo##", oCustomVettingResult.IDNo);
                            int.TryParse(oCustomVettingResult.EnquiryID.ToString(), out EnquiryID);

                            oSMSResult = await _serviceEngine.SMSAlertAsync(Session["XDSWSAuthToken"].ToString(),
                                !string.IsNullOrEmpty(model.MobileNo) ? model.MobileNo : model.AlternateMobileNo, strSMSMessage, Session["SMSAlertType"].ToString(), EnquiryID, int.Parse(Session["SMSProductID"].ToString()));
                        }
                    }
                    #endregion
                }
            }

            return PartialViewHelper("_CustomVettingReportPartial", rpt);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CustomVettingHistoryReport(HistoryMatchViewModel model)
        {
            //ViewBag.Message = "Your create enquiry page.";
            if (ModelState.IsValid)
            {
                CustomVetting rpt = null;

                rpt = await _serviceEngine.CustomVettingGetTransactionEnquiryAsync(Session["AuthToken"].ToString(), model.EnquiryID);

                Session["ReportXML"] = _serviceEngine.ReportXML();

                return PartialViewHelper("_CustomVettingReportPartial", rpt);

            }
            return null;
        }
    }
}

XDS.ONLINE.WEB/Controllers/PromotionDealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XDS.ONLINE.ENGINE;
using XDS.ONLINE.MODELS;
using System.Threading.Tasks;
using System.Web.Routing;
using System.Xml.Linq;
using System.Xml;

namespace XDS.ONLINE.WEB.Controllers
{
    public class PromotionDealController : BaseXDSEngineController
    {

        public PromotionDealController()
        {
        }

        public PromotionDealController(IXDSServiceEngine serviceEngine)
        {
            _serviceEngine = serviceEngine;
        }

        //
        // GET: /CustomVetting/
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> PromotionDealMatch()
        {
            ViewBag.Message = "";
            ViewBag.ProductID = "110";

            ListofPromotionDeals em = new ListofPromotionDeals();

            em = await _serviceEngine.GetPromotionDealsAsync(Session["AuthToken"].ToString(), 0);

            return View(em);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PromotionDealMatch(string Portfolio)
        {
            ListofPromotionDeals em = null;

            em = _serviceEngine.GetPromotionDealsByPortfolio(Session["AuthToken"].ToString(), Portfolio);

            return View(em);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetPromotionDeal(long PromotionDealID)
        {
            ListofPromotionDeals em = null;
            ListofPortfolios emPortfolio = null;

            PromotionDealItem oPromotionDealItem = null;

            em = _serviceEngine.GetPromotionDeals(Session["AuthToken"].ToString(), PromotionDealID);
            emPortfolio = _serviceEngine.GetPortfoliosByPromotionDeal(Session["AuthToken"].ToString(), PromotionDealID);

            if (em != null && em.PromotionDealList.Count() > 0)
            {
                oPromotionDealItem = em.PromotionDealList[0];

                oPromotionDealItem.PromotionDealPortfolios = emPortfolio;

                if (oPromotionDealItem.Doc != null)
                    oPromotionDealItem.Image = string.Format("data:{0};base64,{1}", oPromotionDealItem.DocContentType, Convert.ToBase64String(oPromotionDealItem.Doc));
            }

            return PartialView("_PromotionDealPartial", oPromotionDealItem);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetPortfoliosByPromotionDeal(long PromotionDealID)
        {
            ListofPortfolios em = null;

            em = _serviceEngine.GetPortfoliosByPromotionDeal(Session["AuthToken"].ToString(), PromotionDealID);

            return PartialView("_PortfolioPartial", em);
        }
    }
}

XDS.ONLINE.WEB/Controllers/VideoTrainingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XDS.ONLINE.ENGINE;
using XDS.ONLINE.MODELS;
using System.Threading.Tasks;
using System.Web.Routing;
using System.Xml.Linq;
using System.Xml;

namespace XDS.ONLINE.WEB.Controllers
{
    public class VideoTrainingController : BaseXDSEngineController
    {

        public VideoTrainingController()
        {
        }

        public VideoTrainingController(IXDSServiceEngine serviceEngine)
        {
            _serviceEngine = serviceEngine;
        }

        //
        // GET: /CustomVetting/
        public ActionResult Index()
        {
            return View();
        } 

        [HttpGet]
        public async Task<ActionResult> VideoTrainingMatch()
        {
            ViewBag.Message = "";
            ViewBag.ProductID = "110";

            ListofTrainingDoc em = new ListofTrainingDoc();

            em = await _serviceEngine.CustomVettingGetTrainingDocAsync(Session["AuthToken"].ToString()); 

            return View(em);
        } 

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DownloadTrainingDoc(long TrainingID)
        {
            ListofTrainingDoc em = null;

            em = _serviceEngine.CustomVettingGetTrainingDocFile(Session["AuthToken"].ToString(), TrainingID);

            if (em != null && em.TrainingDocList.Count() > 0)
            {
                string Applicatuionpath = HttpRuntime.AppDomainAppPath;
                string file =  "/TrainingVideo/";

                if (!System.IO.Directory.Exists(Applicatuionpath + "/" + file))
                {
                    System.IO.Directory.CreateDirectory(Applicatuionpath + "/" + file);
                }

                file = file + DateTime.Now.ToString("yyyyMMddhhmmss")+"_Training.mp4";
                em.TrainingDocList[0].VideofileLocation = System.Web.HttpContext.Current.Request.ApplicationPath+file;
                

                System.IO.File.WriteAllBytes(Applicatuionpath +"/"+ file, em.TrainingDocList[0].TrainingDoc);
            }

            return View("../VideoTraining/ViewTrainingContent", em);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public void ClearMedia(string Videoabsolutepath)
        {
            Videoabsolutepath = Videoabsolutepath.Replace(System.Web.HttpContext.Current.Request.ApplicationPath, string.Empty);
            if (System.IO.File.Exists(HttpRuntime.AppDomainAppPath + "/"+ Videoabsolutepath))
            {
                System.IO.File.Delete(HttpRuntime.AppDomainAppPath + "/" + Videoabsolutepath);
            }
           
        }
    }
}

XDS.ONLINE.WEB/Views/Shared/_EnquiryInputPartial.cshtml
@model XDS.ONLINE.MODELS.ConsumerSubscriberInputDetails 

<div class="panel panel-primary">
    <div class="panel-heading">Enquiry Input Details</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-3">Enquiry Date:</div>
            <div class="col-md-3"><strong>@(XDS.ONLINE.MODELS.General.DisplayDateWithTime(Model.EnquiryDate.ToString()))</strong></div>
            <div class="col-md-3">Enquiry Type:</div>
            <div class="col-md-3"><strong>@Model.EnquiryType</strong></div>
        </div>
        <div class="row">
            <div class="col-md-3">Subscriber Name:</div>
            <div class="col-md-3"><strong>@Model.SubscriberName</strong></div>
            <div class="col-md-3">Subscriber User Name:</div>
            <div class="col-md-3"><strong>@Model.SubscriberUserName</strong></div>
        </div>
        <div class="row">
            <div class="col-md-3">Enquiry Input:</div>
            <div class="col-md-3"><strong>@Model.EnquiryInput</strong></div>
            
            @if (!string.IsNullOrEmpty(Model.EnquiryReason))
            {
                <div class="col-md-3">Enquiry Reason:</div>  
                <div class="col-md-3"><strong>@Model.EnquiryReason</strong></div>
            }
        </div>
    </div>
</div>

XDS.ONLINE.WEB/Views/Shared/_ExportButtonsReportPartial.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
</head>
<body>
        <div class="col-md-9 text-right">
            <button id="btnExportPDF" class="btn btn-primary" onclick="exportReport('PDF');"><i class="glyphicon glyphicon-paperclip"></i> PDF</button>
            <button id="btnExportIMAGE" class="btn btn-primary" onclick="exportReport('IMAGE');"><i class="glyphicon glyphicon-picture"></i> IMAGE</button>
            <button id="btnExportHTML" class="btn btn-primary" onclick="exportReport('HTML');"><i class="glyphicon glyphicon-file"></i> HTML</button> 
        </div>
</body>
</html>

XDS.ONLINE.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>XDS - @ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6v5-2uaq_wusHDktM9ILcqIrlPtnZgEk" type="text/javascript"></script>
    @Styles.Render("~/Content/css")
    @RenderSection("head", required: false)
    @Styles.Render("~/Content/chosen.css" )
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="">
        <div class="navbar-header">
            <button type="button" id="toggle-btn" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Content("~/")">
                <img src="@Url.Content("~/images/vodacomlogo.png")" class="logo" border="0" />
            </a>

        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right" style="font-size: 12px;">


            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="glyphicon glyphicon-user"></i>@{if (Session["DisplayName"] != null)
                        { @Session["DisplayName"].ToString()} }
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>
                        <a href="@Url.Action("UserProfile", "UserProfile")"><i class="glyphicon glyphicon-user"></i> User Profile</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ChangePassword", "ChangePassword")"><i class="glyphicon glyphicon-cog"></i> Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="@Url.Action("LogOff", "Account")"><i class="glyphicon glyphicon-log-out"></i> Logout</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="glyphicon glyphicon-info-sign"></i> @ViewContext.Controller.GetType().Assembly.GetName().Version</a></li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <li>
                <a href="@Url.Action("LogOff", "Account")"><i class="glyphicon glyphicon-log-out"></i> Logout</a>
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        @if (Session["Survey"] == "1")
        {
        }
        else
        {

            <div id="sidebar-main" class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">

                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="@Url.Action("HistoryMatch", "History")"><i class="glyphicon glyphicon-search"></i> History</a>
                        </li>
                        <li>
                            <a href="@Url.Action("CustomVettingMatch", "CustomVetting")"><i class="glyphicon glyphicon-th"></i> New Application</a>
                        </li>
                        <li>
                            <a href="@Url.Action("BulletinMatch", "Bulletin")"><i class="glyphicon glyphicon-download-alt"></i> Bulletins</a>
                        </li>
                        <li>
                            <a href="@Url.Action("VideoTrainingMatch", "VideoTraining")"><i class="glyphicon glyphicon-facetime-video"></i> Video Training</a>
                        </li>
                        <li>
                            <a href="@Url.Action("PromotionDealMatch", "PromotionDeal")"><i class="glyphicon glyphicon-screenshot"></i> Available Deals</a>
                        </li>
                    </ul>

                </div>
                <!-- /.sidebar-collapse -->
            </div>
        }
        <!-- /.navbar-static-side -->

    </nav>
    <div id="SubscriberDetails" class="subscriberDIV"></div>


    <div id="page-wrapper" style="">
        @RenderSection("featured", required: false)
        <div class="row">
            <h3>@ViewBag.Title</h3>
            @RenderBody()
        </div>
    </div>

    <div class="modal fade" id="gloading" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">
                        <img src="@Url.Content("~/images/ajax-loader.gif")" />
                        Loading...
                    </h4>
                </div>
                <div class="modal-body">
                    Your request is busy processing.
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="gBonusSegments" tabindex="-1" role="dialog" aria-labelledby="gBonusSegmentsLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="gBonusSegmentsLabel">XDS Trace Plus</h4>
                </div>
                <div class="modal-body" id="gBonusSegmentsBody"></div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-md-8 error">
                            All selected modules will be charged at an additional cost
                        </div>
                        <div class="col-md-4 right">
                            <button type="button" class="btn btn-primary" onclick="fetchReportBonus();">Submit</button>
                            <button type="button" class="btn btn-primary" onclick="HideBonusSegmentsAndFetchReport();">Skip</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="gEmailReport" tabindex="-1" role="dialog" aria-labelledby="gEmailReportLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg small">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="gEmailReportLabel">XDS Report Request</h4>
                </div>
                <div class="modal-body" id="gEmailReportBody"></div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="gBusinessSegments" tabindex="-1" role="dialog" aria-labelledby="gBusinessSegmentsLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="gBusinessSegmentsLabel">XDS Business Enquiry</h4>
                </div>
                <div class="modal-body" id="gBusinessSegmentsBody"></div>
                <div class="modal-footer">
                    <div class="row">
                        @*<div class="col-md-8 error">
                                All selected modules will be charged at an additional cost
                            </div>*@
                        <div class="col-md-4 right">
                            <button type="button" class="btn btn-primary" onclick="fetchBusinessReportBonus();">Submit</button>
                            @*<button type="button" class="btn btn-primary" onclick="HideBusinessBonusSegmentsAndFetchReport(false);">Cancel</button>*@
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="gAuthenticationSegments" tabindex="-1" role="dialog" aria-labelledby="gBusinessSegmentsLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="gAuthenticationSegmentsLabel">XDS Authentication Enquiry</h4>
                </div>

                <div id="gAuthenticationSegmentsBody"></div>

            </div>
        </div>
    </div>
    <div class="modal fade" id="myLinksModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myLinksModalLabel">XDS Linkage Enquiry</h4>
                </div>

                <div id="modalLinkDataSubmitBody">

                    @*<div class="modal-body">

                              <div class="row">

                                   <div class="col-md-12">

                                          <table class="table table-striped">

                                              <tr>
                                                  <td>
                                                      <input type="radio" id="rb1" name="idlinkgroup" value="/TraceEnquiry/ConsumerMatchLink" />
                                                  </td>
                                                  <td>
                                                      <label>Consumer Trace</label>
                                                  </td>
                                              </tr>
                                              <tr>
                                                  <td>
                                                      <input type="radio" id="rb2" name="idlinkgroup" value="/Verification/IDVerificationMatchLink" />
                                                  </td>
                                                  <td>
                                                      <label>Identity Verification Trace</label>
                                                  </td>
                                              </tr>
                                              <tr>
                                                  <td>
                                                      <input type="radio" id="rb3" name="idlinkgroup" value="/CommercialEnquiry/PrincipalEnquiryMatchLink" />
                                                  </td>
                                                  <td>
                                                      <label>Principal Enquiry</label>
                                                  </td>
                                              </tr>
                                              <tr>
                                                  <td>
                                                      <input type="radio" id="rb4" name="idlinkgroup" value="/PublicInfoEnquiry/PublicDomainEnquiryMatchLink" />
                                                  </td>
                                                  <td>
                                                      <label>Full Public Domain Enquiry</label>
                                                  </td>
                                              </tr>

                                          </table>

                                      </div>

                              </div>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <button type="button" class="btn btn-primary" id="btnSendChoice" onclick="LoadChoicesID();">Send</button>
                        </div>*@

                </div>

                <form id="linkform" action="/TraceEnquiry/ConsumerMatchLink" method="POST">
                    <input type="hidden" name="jsonData" id="jsonData" />
                    <input type="hidden" name="selectedVal" id="selectedVal" />
                </form>

            </div>
        </div>
    </div>

    <div class="modal fade" id="gPromotionDeal" tabindex="-1" role="dialog" aria-labelledby="gPromotionDealLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="gPromotionDealTitleLabel">Promotion Deal</h4>
                </div>

                <div id="gPromotionDealBody"></div> 
            </div>
        </div>
    </div>
     
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/applicationjs")
    @RenderSection("scripts", required: false)
    <script language="javascript">
        //if (window.location.protocol == "http:") {
        //    var restOfUrl = window.location.href.substr(5);
        //    window.location = "https:" + restOfUrl;
        //}
        contextUrl = '@Url.Content("~")';
    </script>

</body>
</html>